# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Tile" data-toc-modified-id="Tile-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Tile</a></div><div class="lev2 toc-item"><a href="#Exemplo-unidimensional---replicando-as-colunas" data-toc-modified-id="Exemplo-unidimensional---replicando-as-colunas-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Exemplo unidimensional - replicando as colunas</a></div><div class="lev2 toc-item"><a href="#Exemplo-unidimensional---replicando-as-linhas" data-toc-modified-id="Exemplo-unidimensional---replicando-as-linhas-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Exemplo unidimensional - replicando as linhas</a></div><div class="lev2 toc-item"><a href="#Exemplo-bidimensional---replicando-as-colunas" data-toc-modified-id="Exemplo-bidimensional---replicando-as-colunas-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Exemplo bidimensional - replicando as colunas</a></div><div class="lev2 toc-item"><a href="#Exemplo-bidimensional---replicando-as-linhas" data-toc-modified-id="Exemplo-bidimensional---replicando-as-linhas-14"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Exemplo bidimensional - replicando as linhas</a></div><div class="lev2 toc-item"><a href="#Exemplo-bidimensional---replicando-as-linhas-e-colunas-simultaneamente" data-toc-modified-id="Exemplo-bidimensional---replicando-as-linhas-e-colunas-simultaneamente-15"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Exemplo bidimensional - replicando as linhas e colunas simultaneamente</a></div><div class="lev1 toc-item"><a href="#Documentação-Oficial-Numpy" data-toc-modified-id="Documentação-Oficial-Numpy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Documentação Oficial Numpy</a></div>

# Tile

Uma função importante da biblioteca numpy é a tile, que gera repetições do array passado com parâmetro. A quantidade de repetições é dada pelo parâmetro reps

## Exemplo unidimensional - replicando as colunas

In [10]:
import numpy as np

a = np.array([0, 1, 2])
print('a = \n', a)

print()
print('Resultado da operação np.tile(a,2): \n',np.tile(a,2))

a = 
 [0 1 2]

Resultado da operação np.tile(a,2): 
 [0 1 2 0 1 2]


## Exemplo unidimensional - replicando as linhas

Para modificar as dimensões na quais a replicação será realizada modifica-se o parâmetro reps, passando ao invés de um int, uma tupla com as dimensões que se deseja alterar

In [9]:
print('a = \n', a)
print()
print("Resultado da operação np.tile(a,(2,1)):\n" , np.tile(a,(2,1)))

a = 
 [[0 1]
 [2 3]]

Resultado da operação np.tile(a,(2,1)):
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]


## Exemplo bidimensional - replicando as colunas

In [8]:
a = np.array([[0, 1], [2, 3]])
print('a = \n', a)
print()

print("Resultado da operação np.tile(a,2):\n", np.tile(a,2))

a = 
 [[0 1]
 [2 3]]

Resultado da operação np.tile(a,2):
 [[0 1 0 1]
 [2 3 2 3]]


## Exemplo bidimensional - replicando as linhas

In [14]:
a = np.array([[0, 1], [2, 3]])
print('a = \n', a)

print()
print("Resultado da operação np.tile(a,(3,1)):\n", np.tile(a,(3,1)))

a = 
 [[0 1]
 [2 3]]

Resultado da operação np.tile(a,(3,1)):
 [[0 1]
 [2 3]
 [0 1]
 [2 3]
 [0 1]
 [2 3]]


## Exemplo bidimensional - replicando as linhas e colunas simultaneamente

In [16]:
a = np.array([[0, 1], [2, 3]])
print('a = \n', a)

print()
print("Resultado da operação np.tile(a,(2,2)):\n", np.tile(a,(2,2)))

a = 
 [[0 1]
 [2 3]]

Resultado da operação np.tile(a,(2,2)):
 [[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]


# Documentação Oficial Numpy

- [tile](http://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html)
- [repeat](http://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html)
