# Analysis of Ramp program solutions

This page presents the main solutions presented in the Rampa program.
The objective is to understand the discrepancies between them and compare their advantages and disadvantages.

Conceptual solution with indices:
===============================

In this approach, the coordinate matrix of the "c" columns is already the desired ramp. The only care is that
as one of the test values the ramp exceeds the value 255, it is important that the type of
pixel is an integer with at least 16 bits.

In [19]:
def rr_indices( lado):
    import numpy as np
    r,c = np.indices( (lado, lado), dtype='uint16' )
    return c
    
print(rr_indices(11))

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]


More efficient solutions:
=========================

There are at least three solutions that are classified as the most efficient.
All of them have the cost of writing a line and then copying this line
on every line of the output image.

Broadcast copy
-------------------

The most interesting and most efficient is broadcast copying (subject of module 3).
This solution declares the
final image with empty and then copy a line created by range to
each line of the image using numpy's broadcast property.

In [20]:
def rr_broadcast( side):
    import numpy as np
    row = np.arange(side, dtype='uint16')
    g = np.empty ( (side,side), dtype='uint16')
    g[:,:] = row
    return g

print(rr_broadcast(11))

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]


Copy in tile form
--------------------------
In the solution using tile, a tile is created
with the ramp line through ``arange`` and then tile this line
with "side" lines.

In [21]:
def rr_tile( side):
    import numpy as np
    f = np.arange(side, dtype='uint16')
    return np.tile( f, (lado,1))

print(rr_tile(11))

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]


Using resize
-----------------

The resize solution uses the numpy resize function property
which completes the image raster by repeating it to the final size.

In [22]:
def rr_resize( step):
    import numpy as np
    f = np.arange(step, dtype='uint16')
    return np.resize(f, (step,step))
        
print(rr_resize(11))

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]


Using repeat
-----------------

repeat to numpy repeats each pixel n times. To use it in this
problem, repeating the ramp line (arange) on each side, after
reformat it to two dimensions there is a need to do the transposition
because repetition occurs horizontally and what we want is repetition in
vertical, because in the final image the lines are repeated.

In [23]:
def rr_repeat( side):
    import numpy as np
    f = np.arange(side, dtype='uint16')
    return np.repeat( f, side).reshape(side, side).transpose()

print(rr_repeat(11))

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]


Using the modulo operation
----------------------------

A solution that was not found is the one that uses the "module" operator, that is,
the rest of the division. In this solution, a unique vector of the final size of the
image, applying the "modulo side" operator. Then just reformat it to
two dimensions. The drawback of this solution is that the vector needs to be 32
bits, as the total number of pixels is typically greater than 65535, which is the maximum
which can be represented in 'uint16'.
     

In [24]:
def rr_module( side):
    import numpy as np
    f = np.arange(side * side, dtype='int32')
    return (f % side).reshape(side,side)
    
print(rr_module(11))

[[ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]
 [ 0  1  2  3  4  5  6  7  8  9 10]]


Testing
=====================

In [25]:
p = [rr_broadcast, rr_resize, rr_repeat, rr_tile, rr_indices, rr_modulo]
side = 101
f    = rr_indices(side)
for func in p:
    if not (func(side) == f).all():
        print('func %s failed' % func.__name__)

Comparing time
================

The time for each function is calculated by running it a thousand times and calculating the 2nd percentile.

In [26]:
import numpy as np

p = [rr_broadcast, rr_tile, rr_resize, rr_repeat, rr_modulo, rr_indices]
side = 20057
for func in p:
    print(func.__name__)
    %timeit f = func(side)
    print()

rr_broadcast
1 loop, best of 3: 638 ms per loop

rr_tile
1 loop, best of 3: 621 ms per loop

rr_resize
1 loop, best of 3: 625 ms per loop

rr_repeat
1 loop, best of 3: 2.54 s per loop

rr_modulo
1 loop, best of 3: 4.59 s per loop

rr_indices
1 loop, best of 3: 1.32 s per loop



References
===========

- `master:tutorial_numpy_1_8 Adessowiki: tile exemplos ilustrativos`
- `http://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html NumPy: tile`
- `http://docs.scipy.org/doc/numpy/reference/generated/numpy.repeat.html NumPy: repeat`