# Slicing in two-dimensional ndarray

An important feature of numpy is slicing, in which it is possible to access parts of the array in different ways, as can be seen below:

## Initializing an array and changing its shape

In [1]:
%matplotlib inline
import numpy as np
from PIL import Image

In [2]:
a = np.arange(20) # a is a one-dimensional vector of 20 elements
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [3]:
a = a.reshape(4,5) # a is now a 4x5 matrix (4 rows by 5 columns)
print('a.reshape(4,5) = \n', a)

a.reshape(4,5) = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Slicing rows and columns of an array

The : operator indicates that all elements in that dimension must be accessed.

In [4]:
print('The second line of the array: \n', a[1,:]) # The second line is index 1

print(' The first column of the array: \n', a[:,0]) # The first column corresponds to index 0

The second line of the array: 
 [5 6 7 8 9]
 The first column of the array: 
 [ 0  5 10 15]


## Slicing specific elements of an array

In [5]:
print('Accessing the rows of the array 2 by 2 starting at index 0: \n',
       a[0::2,:])

print(' Accessing the rows and columns of the array 2 by 2 starting with row 0 and column 1: \n',
       a[0::2,1::2])

Accessing the rows of the array 2 by 2 starting at index 0: 
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]
 Accessing the rows and columns of the array 2 by 2 starting with row 0 and column 1: 
 [[ 1  3]
 [11 13]]


## Fatiamento com índices invertidos

In [6]:
print("Access the last two lines of the array in reverse order:\n",
       a[-1:-3:-1,:])
print("Access element in the last row and column of the array:\n",
       a[-1,-1])
print("Reversing the order of the array rows:\n",
      a[::-1,:])

Access the last two lines of the array in reverse order:
 [[15 16 17 18 19]
 [10 11 12 13 14]]
Access element in the last row and column of the array:
 19
Reversing the order of the array rows:
 [[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


# Numpy Official Documentation

[Scipy.org Array Indexing Basics](https://docs.scipy.org/doc/numpy/user/basics.indexing.html)

# Interesting Links

[Scipy-lectures: advanced operations with slicing](http://scipy-lectures.github.io/intro/numpy/array_object.html#fancy-indexing)