# Table of Contents
 <p><div class="lev1 toc-item"><a href="#Numpy:-Funções-indices-e-meshgrid" data-toc-modified-id="Numpy:-Funções-indices-e-meshgrid-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy: Funções indices e meshgrid</a></div><div class="lev2 toc-item"><a href="#Operador-indices-em-pequenos-exemplos-numéricos" data-toc-modified-id="Operador-indices-em-pequenos-exemplos-numéricos-11"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Operador indices em pequenos exemplos numéricos</a></div><div class="lev2 toc-item"><a href="#Operador-indices-em-exemplo-de-imagens-sintéticas" data-toc-modified-id="Operador-indices-em-exemplo-de-imagens-sintéticas-12"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Operador indices em exemplo de imagens sintéticas</a></div><div class="lev2 toc-item"><a href="#Soma" data-toc-modified-id="Soma-13"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Soma</a></div><div class="lev2 toc-item"><a href="#Subtração" data-toc-modified-id="Subtração-14"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Subtração</a></div><div class="lev2 toc-item"><a href="#Xadrez" data-toc-modified-id="Xadrez-15"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Xadrez</a></div><div class="lev2 toc-item"><a href="#Reta" data-toc-modified-id="Reta-16"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Reta</a></div><div class="lev2 toc-item"><a href="#Parábola" data-toc-modified-id="Parábola-17"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Parábola</a></div><div class="lev2 toc-item"><a href="#Círculo" data-toc-modified-id="Círculo-18"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Círculo</a></div><div class="lev2 toc-item"><a href="#Meshgrid" data-toc-modified-id="Meshgrid-19"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Meshgrid</a></div><div class="lev2 toc-item"><a href="#Gerando-os-vetores-com-linspace" data-toc-modified-id="Gerando-os-vetores-com-linspace-110"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Gerando os vetores com linspace</a></div><div class="lev2 toc-item"><a href="#Exemplo-na-geração-da-imagem-sinc-com-meshgrid" data-toc-modified-id="Exemplo-na-geração-da-imagem-sinc-com-meshgrid-111"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Exemplo na geração da imagem sinc com meshgrid</a></div><div class="lev2 toc-item"><a href="#Exemplo-na-geração-da-imagem-sinc-com-indices" data-toc-modified-id="Exemplo-na-geração-da-imagem-sinc-com-indices-112"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Exemplo na geração da imagem sinc com indices</a></div><div class="lev2 toc-item"><a href="#Documentação-Oficial-Numpy" data-toc-modified-id="Documentação-Oficial-Numpy-113"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Documentação Oficial Numpy</a></div><div class="lev2 toc-item"><a href="#Referências" data-toc-modified-id="Referências-114"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>Referências</a></div><div class="lev2 toc-item"><a href="#Para-usuários-avançados" data-toc-modified-id="Para-usuários-avançados-115"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>Para usuários avançados</a></div><div class="lev2 toc-item"><a href="#Exemplos-com-Imagem" data-toc-modified-id="Exemplos-com-Imagem-116"><span class="toc-item-num">1.16&nbsp;&nbsp;</span>Exemplos com Imagem</a></div>

# Numpy: Funções indices e meshgrid

As funções ``indices`` e ``meshgrid`` são extremamente úteis na geração de imagens sintéticas e o seu aprendizado permite também
entender as vantagens de programação matricial, evitando-se a varredura seqüencial da imagem muito usual na programação na linguagem C.

## Operador indices em pequenos exemplos numéricos

A função ``indices`` recebe como parâmetros uma tupla com as dimensões (H,W) das matrizes a serem criadas. No exemplo a seguir, estamos
gerando matrizes de 5 linhas e 10 colunas. Esta função retorna uma tupla de duas matrizes que podem ser obtidas fazendo suas atribuições
como no exemplo a seguir onde criamos as matrizes ``r`` e ``c``, ambas de tamanho (5,10), isto é, 5 linhas e 10 colunas:

In [1]:
import numpy as np
r,c = np.indices( (5, 10) )
print('r=\n', r)
print('c=\n', c)

r=
 [[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]]
c=
 [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


Note que a matriz ``r`` é uma matriz onde cada elemento é a sua coordenada linha e a matriz ``c`` é uma matriz onde cada elemento é
a sua coordenada coluna. Desta forma, qualquer operação matricial feita com ``r`` e ``c``, na realidade você está processando as
coordenadas da matriz. Assim, é possível gerar diversas imagens sintéticas a partir de uma função de suas coordenadas.

Como o NumPy processa as matrizes diretamente, sem a necessidade de fazer um ``for`` explícito, a notação do programa fica bem simples
e a eficiência também. O único inconveniente é o uso da memória para se calcular as matrizes de índices ``r`` e ``c``. Iremos
ver mais à frente que isto pode ser minimizado. 

Por exemplo seja a função que seja a soma de suas coordenadas $f(r,c) = r + c$:

In [2]:
f = r + c
print('f=\n', f)

Ou ainda a função diferença entre a coordenada linha e coluna $f(r,c) = r - c$:

In [3]:
f = r - c
print('f=\n', f)

f=
 [[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
 [ 1  0 -1 -2 -3 -4 -5 -6 -7 -8]
 [ 2  1  0 -1 -2 -3 -4 -5 -6 -7]
 [ 3  2  1  0 -1 -2 -3 -4 -5 -6]
 [ 4  3  2  1  0 -1 -2 -3 -4 -5]]


Ou ainda a função $f(r,c) = (r + c) \% 2$ onde % é operador módulo. Esta função retorna 1 se a soma das coordenadas for ímpar e 0 caso contrário.
É uma imagem no estilo de um tabuleiro de xadrez de valores 0 e 1:

In [4]:
f = (r + c) % 2
print('f=\n', f)

f=
 [[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


Ou ainda a função de uma reta $ f(r,c) = (r = \frac{1}{2}c)$:

In [6]:
f = (r == c//2)
print('f=\n', f)
print('f=\n',f.astype(np.int16))

f=
 [[ True  True False False False False False False False False]
 [False False  True  True False False False False False False]
 [False False False False  True  True False False False False]
 [False False False False False False  True  True False False]
 [False False False False False False False False  True  True]]
f=
 [[1 1 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1]]


Ou ainda a função parabólica dada pela soma do quadrado de suas coordenadas 
$$ f(r,c) = r^2 + c^2 $$:

In [7]:
f = r**2 + c**2
print('f=\n', f)

f=
 [[ 0  1  4  9 16 25 36 49 64 81]
 [ 1  2  5 10 17 26 37 50 65 82]
 [ 4  5  8 13 20 29 40 53 68 85]
 [ 9 10 13 18 25 34 45 58 73 90]
 [16 17 20 25 32 41 52 65 80 97]]


   
Ou ainda a função do círculo de raio 4, com centro em (0,0) $f(r,c) = (r^2 + c^2 < 4^2)$:

In [8]:
f = ((r**2 + c**2) < 4**2)
print('f=\n', f * 1)

f=
 [[1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


## Operador indices em exemplo de imagens sintéticas

Vejamos os exemplos acima, porém gerados em imagens. A diferença será no tamanho da matriz, iremos utilizar matriz (200,300), e
a forma de visualizá-la através do ``adshow``, ao invés de imprimir os valores como fizemos acima. 
Como muitas vezes o resultado das funções poderão estar fora
da faixa 0-255 admitida pelo ``adshow``, iremos sempre normalizar os valores finais da imagem calculada para a faixa 0-255 utilizando
a função `ia636:ianormalize ianormalize` da toolbox ia636.

Gerando as coordenadas utilizando ``indices``:

Observe que o parâmetro de ``indices`` é uma tupla. Verifique o número de parêntesis utilizados:

In [ ]:
import numpy as np
import sys,os


In [9]:
r,c = np.indices( (200, 300) )
rn = normalize.normalize(r)
cn = normalize.normalize(c)
plt.imshow(rn,'rn:linhas')


NameError: name 'ia' is not defined

In [ ]:
nb.nbshow(cn,'cn:colunas',flush=True)

## Soma

Função soma: $f(r,c) = r + c$:

In [ ]:
f = r + c
ia.adshow(ia.normalize(f),'r + c')

## Subtração

Função subtração $f(r,c) = r - c$:

In [ ]:
f = r - c
ia.adshow(ia.normalize(f),'r - c')

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.imshow(f,cmap='gray')
plt.colorbar()

## Xadrez

Função xadrez $f(r,c) = \frac{(r + c)}{8} \% 2$. Aqui foi feita a divisão por 8 para que o tamanho das casas do xadrez fique 8 x 8, caso
contrário é muito difícil de visualizar o efeito xadrez pois a imagem possui muitos pixels.:

In [ ]:
f = (r//8 + c//8) % 2
ia.adshow(ia.normalize(f),'(r//8 + c//8) % 2')

## Reta

Ou ainda a função de uma reta $f(r,c) = (r = \frac{1}{2} c)$:

In [ ]:
f = (r == c//2)
ia.adshow(f,'r == c//2')

## Parábola

Função parabólica: $f(r,c) = r^2 + c^2$:

In [ ]:
f = r**2 + c**2
ia.adshow(ia.normalize(f),'r**2 + c**2')

## Círculo

Função do círculo de raio 190, $f(r,c) = (r^2 + c^2 < 190^2)$:

In [ ]:
f = (r**2 + c**2 < 190**2)
ia.adshow(ia.normalize(f),'r**2 + c**2) < 190**2')

## Meshgrid
   
A função ``meshgrid`` é semelhante à  função ``indices`` visto
anteriormente, porém, enquanto ``indices`` gera as coordenadas inteiras não negativas a partir de um ``shape(H,W)``, 
o ``meshgrid`` gera os valores das matrizes a partir de dois vetores de valores reais quaisquer, um para as linhas e outro para as colunas.

Veja a seguir um pequeno exemplo numérico. Para que o ``meshgrid`` fique compatível com a nossa convenção de (linhas,colunas), deve-se
usar o parâmetro ``indexing='ij'``.

In [ ]:
import numpy as np
r, c = np.meshgrid( np.array([-1.5, -1.0, -0.5, 0.0, 0.5]), 
                    np.array([ -20,  -10,    0,  10,  20, 30]), indexing='ij')
print('r=\n',r)
print('c=\n',c)

## Gerando os vetores com linspace

A função ``linspace`` gera vetor em ponto flutuante recebendo os parâmetro de valor inicial, valor final e número de pontos do vetor.
Desta forma ele é bastante usado para gerar os parâmetro para o ``meshgrid``.
 
Repetindo os mesmos valores do exemplo anterior, porém usando ``linspace``. Observe que o primeiro vetor possui 5 pontos,
começando com valor -1.5 e o valor final é 0.5 (inclusive). O segundo vetor possui 6 pontos, começando de -20 até 30:

In [ ]:
rows = np.linspace(-1.5, 0.5, 5)
cols = np.linspace(-20, 30, 6)

print('rows:', rows)
print('cols:', cols)

Usando os dois vetores gerados pelo ``linspace`` no ``meshgrid``:
   

In [ ]:
r, c = np.meshgrid(rows, cols, indexing='ij')
print('r = \n', r)
print('c = \n', c)

Podemos agora gerar uma matriz ou imagem que seja função destes valores. Por exemplo ser o produto deles:

In [ ]:
f = r * c
print('f=\n', f)

## Exemplo na geração da imagem sinc com meshgrid

Neste exemplo, geramos a imagem da função $ sinc(r,c)$ em duas dimensões, nos intervalos na vertical, de -5 a 5 e na
horizontal de -6 a 6. A função sinc é uma função trigonométrica que pode ser utilizada para filtragens.

A equação é dada por:

$$    sinc(r,c) = \frac{\sin(r^2 + c^2)}{r^2 + c^2}, \text{para\ } -5 \leq r \leq 5, -6 \leq c \leq 6 $$

Na origem, tanto r como c são zeros, resultando uma divisão por zero. Entretanto pela teoria dos limites, $\frac{sin(x)}{x}$ é
igual a 1 quando $x$ é igual a zero.
Uma forma de se obter isto em ponto flutuante é somar tanto no numerador como no denominador um *epsilon*, que é a
menor valor em ponto flutuante. Epsilon pode ser obtido pela função ``np.spacing``. 

In [ ]:
e = np.spacing(1) # epsilon to avoid 0/0
rows = np.linspace(-5.0, 5.0, 150) # coordenadas das linhas
cols = np.linspace(-6.0, 6.0, 180) # coordenadas das colunas
r, c = np.meshgrid(rows, cols, indexing='ij') # Grid de coordenadas estilo numpy
z = np.sin(r**2 + c**2 + e) / (r**2 + c**2 + e) # epsilon is added to avoid 0/0
ia.adshow(ia.normalize(z),'Função sinc: sen(r² + c²)/(r²+c²) em duas dimensões')

In [ ]:
plt.imshow(z)
plt.colorbar()

## Exemplo na geração da imagem sinc com indices

Outra forma de gerar a mesma imagem, usando a função ``indices`` é processar os
indices de modo a gerar os mesmos valores relativos à grade de espaçamento regular
acima, conforme ilustrado abaixo:

In [ ]:
n_rows = len(rows)
n_cols = len(cols)
r,c = np.indices((n_rows,n_cols))
r = -5. + 10.*r.astype(float)/(n_rows-1)
c = -6. + 12.*c.astype(float)/(n_cols-1)
zi = np.sin(r**2 + c**2 + e) / (r**2 + c**2 + e) # epsilon is addes to avoid 0/0
ia.adshow(ia.normalize(zi),'Função sinc: sin(r² + c²)/(r²+c²) em duas dimensões')   

Verificando que as duas funções são iguais:

In [ ]:
print('Máxima diferença entre z e zi?', abs(z - zi).max())

In [ ]:
np.exp(-1/2.)

## Documentação Oficial Numpy
 
- [meshgrid](http://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html)
- [indices](http://docs.scipy.org/doc/numpy/reference/generated/numpy.indices.html) 
- [linspace](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)

## Referências

- [Wikipedia: Sinc Function](http://en.wikipedia.org/wiki/Sinc_function)

## Para usuários avançados

Na realidade a função `indices` retorna um único array n-dimensional com uma dimensão a mais que o indicado pelo
shape usado como parâmetro. Assim, quando é feito ``r,c = np.indices((rows,cols))``, r é atribuído para o elemento 0 e
c é atribuído para o elemento 1 do ndarray. No caso do ``meshgrid``, ele retorna tantos arrays quanto forem o número
de vetores passados como parâmetro para ``meshgrid``.

